name: ci

# Run the workflow on any pushes or PRs.
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10

      # NOTE: The following bug has been fixed, but the fix hasn't been
      # upstreamed to the version of nixpkgs pinned in this repo:
      #
      # https://github.com/purescript-contrib/pulp/issues/392
      #
      # Once pulp has been updated, drop '--no-check-main'
      - run: |
          nix-shell ci.nix \
            --command 'bower install && pulp test --no-check-main'
